# Generated by Django 4.2.7 on 2025-10-07 16:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='来源名称')),
                ('url', models.URLField(verbose_name='来源网址')),
                ('type', models.CharField(choices=[('news', '新闻资讯'), ('social', '社交媒体'), ('official', '官方公告'), ('analysis', '分析研报')], default='news', max_length=20, verbose_name='来源类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '新闻来源',
                'verbose_name_plural': '新闻来源',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('summary', models.TextField(blank=True, verbose_name='摘要')),
                ('original_url', models.URLField(unique=True, verbose_name='原文链接')),
                ('category', models.CharField(choices=[('flash', '快讯'), ('article', '文章'), ('report', '研报'), ('announcement', '公告'), ('market', '行情')], default='article', max_length=20, verbose_name='分类')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('sentiment_score', models.FloatField(blank=True, null=True, verbose_name='情感得分')),
                ('importance_score', models.FloatField(default=0.0, verbose_name='重要程度')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_verified', models.BooleanField(default=False, verbose_name='是否核实')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newssource', verbose_name='来源')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-publish_time'],
                'indexes': [models.Index(fields=['publish_time'], name='news_articl_publish_50495a_idx'), models.Index(fields=['category'], name='news_articl_categor_5c78fc_idx'), models.Index(fields=['source'], name='news_articl_source__2047db_idx')],
            },
        ),
    ]
