#!/bin/bash

echo "=== Vim开发指南 ==="
echo ""
echo "基本操作:"
echo "i - 进入插入模式"
echo "Esc - 退出插入模式" 
echo ":w - 保存"
echo ":q - 退出"
echo ":wq - 保存并退出"
echo ":q! - 强制退出不保存"
echo ""
echo "常用命令:"
echo "vim chainflow_backend/news/models.py - 编辑模型"
echo "vim chainflow_backend/news/admin.py - 编辑管理后台"
echo "vim chainflow_backend/news/views.py - 编辑视图(下一步)"
echo ""
echo "导航命令:"
echo "gg - 文件开头"
echo "G - 文件末尾"
echo ":set number - 显示行号"
echo "/搜索词 - 搜索"
